site_name: Cthulhu Fhtagn A Lot
site_description: A Grognard Blog
site_author: Olivier Rey
copyright: Copyleft Olivier Rey 2017-2022 (GNU FDL)
theme:
    name: material
    palette:
        scheme: default
        primary: blue grey
        accent: light blue
    logo: images/Monstre1.png
    favicon: images/favicon.ico
    features:
        - navigation.tabs
#        - navigation.tabs.sticky
        - navigation.sections
        - navigation.indexes
markdown_extensions:
    - toc:
        permalink: "#"
        baselevel: 2
plugins:
    - tags:
        tags_file: tags.md
    - search:
        lang: 
            - en
            - fr
extra_css:
    - css/extra.css
edit_uri: ""
site_dir: site
site_url: https://orey.github.io/blog
nav:
- Home: index.md
- Blog:
    - 'May 2022': 'blog/202205.md'
    - 'November 2021': 'blog/202111.md'
    - 'September 2020': 'blog/202009.md'
    - 'August 2020': 'blog/202008.md'
- 'Liens/Links':
    - 'Liens': links.md
- Etudes/Studies:
    - 'Comparaison des systèmes D6': 'pages/D6-systems.md'
    - 'Target Number dans le système D6': 'pages/D6-TargetNumber.md'
    - 'Combat dans le système D6': 'pages/D6-Combat.md'
    - 'Morphologie du Conte, de Vladimir Propp': 'pages/propp.md'
#    - 'Players Handbook': 'pages/players.md'
#    - 'Game Masters Guide': 'pages/gms.md'
- Tags: tags.md
- About:
    - Author: about.md
    - License: LICENSE.md

