site_name: Cthulhu Fhtagn A Lot
site_description: A Grognard Blog
site_author: Olivier Rey
copyright: Copyleft Olivier Rey 2017-2022 (GNU FDL)
theme:
    name: material
    palette:
        scheme: default
        primary: blue grey
        accent: light blue
    logo: images/Monstre1.png
    favicon: images/favicon.ico
    features:
        - navigation.tabs
#        - navigation.tabs.sticky
        - navigation.sections
        - navigation.indexes
markdown_extensions:
    - toc:
        permalink: "#"
        baselevel: 2
plugins:
    - search:
        lang: 
            - en
            - fr
edit_uri: ""
site_dir: site
site_url: https://orey.github.io/blog
nav:
- Home: index.md
- Blog:
    - 'May 2022': 'blog/202205.md'
    - 'November 2021': 'blog/202111.md'
    - 'September 2020': '2020/202009.md'
    - 'August 2020': '2020/202008.md'
- Pages:
    - 'Many Links': links.md
    - 'Players Handbook': 'manuals/players.md'
    - 'Game Masters Guide': 'manuals/gms.md'
- About:
    - Author: about.md
    - License: LICENSE.md

