site_name: Enterprise-RPG
site_description: RPG for simulating your enterprise
site_author: Olivier Rey
copyright: Copyleft Olivier Rey 2017-2020 - Site licensed under the GNU FDL V3
google_analytics: ['UA-110156293-1', 'orey.github.io']
repo_url: https://github.com/orey/enterprise-rpg/
theme:
    name: material
    palette:
        scheme: slate
        primary: teal
        accent: light blue
    logo: images/logo.png
    favicon: images/favicon.ico
    edit_uri: ""
site_dir: site
nav:
- Home: index.md
- 2020:
    - 'August 2020': '2020/202008.md'
- 'The Game':
    - 'Players Handbook': 'manuals/players.md'
    - 'Game Masters Guide': 'manuals/gms.md'
- About:
    - Author: about.md
    - License: LICENSE.md
    - Links: links.md

