site_name: Cthulhu Fhtagn A Lot
site_description: A Grognard Blog
site_author: Olivier Rey
copyright: Copyleft Olivier Rey 2017-2023 (GNU FDL)
theme:
    name: material
    palette:
        scheme: default
        primary: blue grey
        accent: light blue
    logo: images/Monstre1.png
    favicon: images/favicon.png
    features:
        - navigation.tabs
#        - navigation.tabs.sticky
        - navigation.sections
        - navigation.indexes
markdown_extensions:
    - toc:
        permalink: "#"
        baselevel: 2
plugins:
    - tags:
        tags_file: tags.md
    - search:
        lang: 
            - en
            - fr
extra_css:
    - css/extra.css
edit_uri: ""
site_dir: site
site_url: https://orey.github.io/blog
nav:
- Home: index.md
- Blog:
    - 'Juin 2023': 'blog/202306.md'
    - 'Mai 2023': 'blog/202305.md'
    - 'Janvier 2023': 'blog/202301.md'
    - 'Octobre/novembre 2022': 'blog/202210.md'
    - 'Août/septembre 2022': 'blog/202209.md'
    - 'Juin/juillet 2022': 'blog/202206.md'
    - 'Mai 2022': 'blog/202205.md'
    - 'November 2021': 'blog/202111.md'
    - 'September 2020': 'blog/202009.md'
    - 'August 2020': 'blog/202008.md'
- 'Links/Liens':
    - 'TTRPG websites': links-en.md
    - 'Sites JDR': links.md
- Etudes/Studies:
    - 'Les pouvoirs psychiques dans le JDR': 'pages/psionics.md'
    - 'Brève étude des Game Master Emulator': 'pages/gme.md'
    - 'Comparaison des systèmes D6': 'pages/D6-systems.md'
    - 'Target Number dans le système D6': 'pages/D6-TargetNumber.md'
    - 'Combat dans le système D6': 'pages/D6-Combat.md'
    - 'Analyse des jeux PbtA': 'pages/pbta.md'
    - 'Morphologie du Conte, de Vladimir Propp': 'pages/propp.md'
#    - 'Players Handbook': 'pages/players.md'
#    - 'Game Masters Guide': 'pages/gms.md'
- Downloads:
    - 'Ghostbusters': 'downloads/ghostbusters.md'
    - 'Fighting Fantasy': 'downloads/fighting-fantasy.md'
    - 'Risus': 'downloads/risus.md'
    - 'La grande Liste des intrigues de JDR': 'downloads/grande-liste.md'
    - 'Cthulhu Dark': 'downloads/cthulhu-dark.md'
    - 'Risus pour Méga': 'downloads/mega.md'
    - 'Fudge en une page': 'downloads/fudge.md'
    - 'DungeonSquad!': 'downloads/dungeonsquad.md'
- Tags: tags.md
- About:
    - Author: about.md
    - License: LICENSE.md

