site_name: Enterprise-RPG
site_description: RPG for playing in rough enterprises
site_author: Olivier Rey
copyright: Copyleft Olivier Rey 2017-2020 - Site licensed under the GNU FDL V3
google_analytics: ['UA-110156293-1', 'orey.github.io']
repo_url: https://github.com/orey/enterprise-rpg/
theme:
    name: bootstrap4
site_dir: site
nav:
- Home:
    - 'Index': 'index.md'
    - 'Author': 'about.md'
    - 'License': 'LICENSE.md'
- 2020:
    - 'Characteristics 1': '2020/20200825-3.md'
    - 'What kind of dice?': '2020/20200825-2.md'
    - 'Why an enterprise RPG?': '2020/20200825.md'

